// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMfj1CobwpaP_CjHDKFkNpzwoA1LAHVYs',
    appId: '1:12079896292:web:151a7740d80b51967dfef1',
    messagingSenderId: '12079896292',
    projectId: 'fooddeliveryapp-4a1e6',
    authDomain: 'fooddeliveryapp-4a1e6.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-4a1e6.appspot.com',
    measurementId: 'G-47P9T6K7VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW3ySooSGvwPMOowxl4jyFWSxi9-WXZc0',
    appId: '1:12079896292:android:8fb0f77daad1f1107dfef1',
    messagingSenderId: '12079896292',
    projectId: 'fooddeliveryapp-4a1e6',
    storageBucket: 'fooddeliveryapp-4a1e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWxxcF8e8zCNYCLB4boUgCtLvSprBOZkg',
    appId: '1:12079896292:ios:b3ae5c732c9d34a87dfef1',
    messagingSenderId: '12079896292',
    projectId: 'fooddeliveryapp-4a1e6',
    storageBucket: 'fooddeliveryapp-4a1e6.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );
}
