// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAqfpTIvJKurK1mXm73CzOho1SbgnWV5Tk",
    authDomain: "vegetarian-food-76bdb.firebaseapp.com",
    projectId: "vegetarian-food-76bdb",
    storageBucket: "vegetarian-food-76bdb.appspot.com",
    messagingSenderId: "959995023672",
    appId: "1:959995023672:web:27f0194808ca76d9e131cd",
    measurementId: "G-Z3D1FY5ZQ8",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg36r30Cz0GVFZifBZaryIjSk_nCJvS1c',
    appId: '1:959995023672:android:854ba8b716032968e131cd',
    messagingSenderId: '959995023672',
    projectId: 'vegetarian-food-76bdb',
    storageBucket: 'vegetarian-food-76bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrUEG-lOxaQYFPIdSttpe59Ib5-gwiLL0',
    appId: '1:12079896292:ios:b3ae5c732c9d34a87dfef1',
    messagingSenderId: '959995023672',
    projectId: 'vegetarian-food-76bdb',
    storageBucket: 'vegetarian-food-76bdb.appspot.com',
    iosBundleId: 'com.example.vegetarianFood',
  );
}
